dist: xenial
language: shell
cache:
  directories:
    - $HOME/.cargo
before_cache:
  - cargo install --debug --git https://github.com/matthiaskrgr/cargo-cache \
      --no-default-features --features ci-autoclean \
      --bin cargo-cache -- cargo-cache
  - cargo cache
install:
  - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
  - curl -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal --default-toolchain="${MIRI_NIGHTLY}" -c miri
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cargo miri setup
script:
  - make api
  - cargo clean
  - cargo miri test
